export const STATIC_REAL_ROUTE_CANDIDATES = {
  "종로구": [
    {
      "place_name": "창신동쪽방촌 온기창고",
      "district": "종로구",
      "district_normalized": "종로구",
      "place_type": "복지시설",
      "address": "서울특별시 종로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 2.0057,
      "is_fallback": false
    },
    {
      "place_name": "대학로 마로니에공원",
      "district": "종로구",
      "district_normalized": "종로구",
      "place_type": "공원",
      "address": "서울특별시 종로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7168,
      "is_fallback": false
    },
    {
      "place_name": "세종대로 사거리 광화문광장",
      "district": "종로구",
      "district_normalized": "종로구",
      "place_type": "교통거점",
      "address": "서울특별시 종로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6818,
      "is_fallback": false
    },
    {
      "place_name": "서울배달라이더 현장",
      "district": "종로구",
      "district_normalized": "종로구",
      "place_type": "교통거점",
      "address": "서울특별시 종로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6458,
      "is_fallback": false
    },
    {
      "place_name": "북촌의 봄",
      "district": "종로구",
      "district_normalized": "종로구",
      "place_type": "전통시장",
      "address": "서울특별시 종로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5081,
      "is_fallback": false
    },
    {
      "place_name": "세종마을 음식문화거리",
      "district": "종로구",
      "district_normalized": "종로구",
      "place_type": "전통시장",
      "address": "서울특별시 종로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5081,
      "is_fallback": false
    },
    {
      "place_name": "창신동 문구완구거리",
      "district": "종로구",
      "district_normalized": "종로구",
      "place_type": "전통시장",
      "address": "서울특별시 종로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5081,
      "is_fallback": false
    },
    {
      "place_name": "청년서울살이 현장",
      "district": "종로구",
      "district_normalized": "종로구",
      "place_type": "전통시장",
      "address": "서울특별시 종로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.459,
      "is_fallback": false
    }
  ],
  "중구": [
    {
      "place_name": "서울장애인종합복지관",
      "district": "중구",
      "district_normalized": "중구",
      "place_type": "복지시설",
      "address": "서울특별시 중구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 2.0497,
      "is_fallback": false
    },
    {
      "place_name": "장충체육관",
      "district": "중구",
      "district_normalized": "중구",
      "place_type": "공원",
      "address": "서울특별시 중구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7437,
      "is_fallback": false
    },
    {
      "place_name": "훈련원근린공원",
      "district": "중구",
      "district_normalized": "중구",
      "place_type": "공원",
      "address": "서울특별시 중구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7419,
      "is_fallback": false
    },
    {
      "place_name": "손기정체육공원",
      "district": "중구",
      "district_normalized": "중구",
      "place_type": "공원",
      "address": "서울특별시 중구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7238,
      "is_fallback": false
    },
    {
      "place_name": "돈화문 사거리",
      "district": "중구",
      "district_normalized": "중구",
      "place_type": "교통거점",
      "address": "서울특별시 중구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6597,
      "is_fallback": false
    },
    {
      "place_name": "신당역",
      "district": "중구",
      "district_normalized": "중구",
      "place_type": "교통거점",
      "address": "서울특별시 중구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6597,
      "is_fallback": false
    },
    {
      "place_name": "정동길 투썸플레이스",
      "district": "중구",
      "district_normalized": "중구",
      "place_type": "전통시장",
      "address": "서울특별시 중구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5954,
      "is_fallback": false
    },
    {
      "place_name": "투썸플레이스 정동길점",
      "district": "중구",
      "district_normalized": "중구",
      "place_type": "전통시장",
      "address": "서울특별시 중구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5954,
      "is_fallback": false
    }
  ],
  "용산구": [
    {
      "place_name": "용산역",
      "district": "용산구",
      "district_normalized": "용산구",
      "place_type": "교통거점",
      "address": "서울특별시 용산구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "용문전통시장",
      "district": "용산구",
      "district_normalized": "용산구",
      "place_type": "전통시장",
      "address": "서울특별시 용산구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5914,
      "is_fallback": false
    },
    {
      "place_name": "효창운동장",
      "district": "용산구",
      "district_normalized": "용산구",
      "place_type": "공원",
      "address": "서울특별시 용산구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5253,
      "is_fallback": false
    },
    {
      "place_name": "용산역 일대",
      "district": "용산구",
      "district_normalized": "용산구",
      "place_type": "교통거점",
      "address": "서울특별시 용산구 용산역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.1176,
      "is_fallback": false
    },
    {
      "place_name": "신용산역 일대",
      "district": "용산구",
      "district_normalized": "용산구",
      "place_type": "교통거점",
      "address": "서울특별시 용산구 신용산역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.0034,
      "is_fallback": false
    },
    {
      "place_name": "신용산역(용산역) 일대",
      "district": "용산구",
      "district_normalized": "용산구",
      "place_type": "골목상권",
      "address": "서울특별시 용산구 신용산역(용산역) 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_worker_csv",
      "candidate_source": "commercial_worker_csv",
      "score": 0.9502,
      "is_fallback": false
    },
    {
      "place_name": "녹사평(용산구청)역 일대",
      "district": "용산구",
      "district_normalized": "용산구",
      "place_type": "교통거점",
      "address": "서울특별시 용산구 녹사평(용산구청)역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 0.9401,
      "is_fallback": false
    },
    {
      "place_name": "용산전자상가(용산역) 일대",
      "district": "용산구",
      "district_normalized": "용산구",
      "place_type": "골목상권",
      "address": "서울특별시 용산구 용산전자상가(용산역) 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9196,
      "is_fallback": false
    }
  ],
  "성동구": [
    {
      "place_name": "서울숲",
      "district": "성동구",
      "district_normalized": "성동구",
      "place_type": "공원",
      "address": "서울특별시 성동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7505,
      "is_fallback": false
    },
    {
      "place_name": "응봉공원 (대현산배수지공원)",
      "district": "성동구",
      "district_normalized": "성동구",
      "place_type": "공원",
      "address": "서울특별시 성동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.743,
      "is_fallback": false
    },
    {
      "place_name": "금호근린공원",
      "district": "성동구",
      "district_normalized": "성동구",
      "place_type": "공원",
      "address": "서울특별시 성동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7412,
      "is_fallback": false
    },
    {
      "place_name": "서울숲 야외무대",
      "district": "성동구",
      "district_normalized": "성동구",
      "place_type": "공원",
      "address": "서울특별시 성동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6875,
      "is_fallback": false
    },
    {
      "place_name": "응봉산 팔각정",
      "district": "성동구",
      "district_normalized": "성동구",
      "place_type": "공원",
      "address": "서울특별시 성동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6875,
      "is_fallback": false
    },
    {
      "place_name": "성수동 골목상권",
      "district": "성동구",
      "district_normalized": "성동구",
      "place_type": "전통시장",
      "address": "서울특별시 성동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6102,
      "is_fallback": false
    },
    {
      "place_name": "성수동 카페거리",
      "district": "성동구",
      "district_normalized": "성동구",
      "place_type": "전통시장",
      "address": "서울특별시 성동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5742,
      "is_fallback": false
    },
    {
      "place_name": "마장동축산물시장",
      "district": "성동구",
      "district_normalized": "성동구",
      "place_type": "전통시장",
      "address": "서울특별시 성동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5542,
      "is_fallback": false
    }
  ],
  "광진구": [
    {
      "place_name": "능동어린이대공원",
      "district": "광진구",
      "district_normalized": "광진구",
      "place_type": "공원",
      "address": "서울특별시 광진구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.791,
      "is_fallback": false
    },
    {
      "place_name": "서울어린이대공원",
      "district": "광진구",
      "district_normalized": "광진구",
      "place_type": "공원",
      "address": "서울특별시 광진구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.791,
      "is_fallback": false
    },
    {
      "place_name": "구의2동 주택재개발 후보지",
      "district": "광진구",
      "district_normalized": "광진구",
      "place_type": "교통거점",
      "address": "서울특별시 광진구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6372,
      "is_fallback": false
    },
    {
      "place_name": "재개발·재건축 현장",
      "district": "광진구",
      "district_normalized": "광진구",
      "place_type": "교통거점",
      "address": "서울특별시 광진구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6372,
      "is_fallback": false
    },
    {
      "place_name": "건대입구 롯데백화점 앞",
      "district": "광진구",
      "district_normalized": "광진구",
      "place_type": "교통거점",
      "address": "서울특별시 광진구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6014,
      "is_fallback": false
    },
    {
      "place_name": "동서울우편집중국",
      "district": "광진구",
      "district_normalized": "광진구",
      "place_type": "교통거점",
      "address": "서울특별시 광진구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6014,
      "is_fallback": false
    },
    {
      "place_name": "건대 맛의거리",
      "district": "광진구",
      "district_normalized": "광진구",
      "place_type": "전통시장",
      "address": "서울특별시 광진구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5411,
      "is_fallback": false
    },
    {
      "place_name": "청년안심주택",
      "district": "광진구",
      "district_normalized": "광진구",
      "place_type": "전통시장",
      "address": "서울특별시 광진구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3199,
      "is_fallback": false
    }
  ],
  "동대문구": [
    {
      "place_name": "밥퍼나눔운동본부",
      "district": "동대문구",
      "district_normalized": "동대문구",
      "place_type": "복지시설",
      "address": "서울특별시 동대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 2.0339,
      "is_fallback": false
    },
    {
      "place_name": "청량리역사거리",
      "district": "동대문구",
      "district_normalized": "동대문구",
      "place_type": "교통거점",
      "address": "서울특별시 동대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "장안동 벚꽃길",
      "district": "동대문구",
      "district_normalized": "동대문구",
      "place_type": "공원",
      "address": "서울특별시 동대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6929,
      "is_fallback": false
    },
    {
      "place_name": "청량리 경동시장 일대",
      "district": "동대문구",
      "district_normalized": "동대문구",
      "place_type": "전통시장",
      "address": "서울특별시 동대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5572,
      "is_fallback": false
    },
    {
      "place_name": "용두근린공원",
      "district": "동대문구",
      "district_normalized": "동대문구",
      "place_type": "공원",
      "address": "서울특별시 동대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3379,
      "is_fallback": false
    },
    {
      "place_name": "동대문역사문화공원역 일대",
      "district": "동대문구",
      "district_normalized": "동대문구",
      "place_type": "골목상권",
      "address": "서울특별시 동대문구 동대문역사문화공원역 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 1.0004,
      "is_fallback": false
    },
    {
      "place_name": "동대문패션타운 관광특구 일대",
      "district": "동대문구",
      "district_normalized": "동대문구",
      "place_type": "골목상권",
      "address": "서울특별시 동대문구 동대문패션타운 관광특구 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9945,
      "is_fallback": false
    },
    {
      "place_name": "동대문역 일대",
      "district": "동대문구",
      "district_normalized": "동대문구",
      "place_type": "교통거점",
      "address": "서울특별시 동대문구 동대문역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 0.9854,
      "is_fallback": false
    }
  ],
  "중랑구": [
    {
      "place_name": "중랑 서울장미축제",
      "district": "중랑구",
      "district_normalized": "중랑구",
      "place_type": "공원",
      "address": "서울특별시 중랑구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.838,
      "is_fallback": false
    },
    {
      "place_name": "먹골역 7번출구",
      "district": "중랑구",
      "district_normalized": "중랑구",
      "place_type": "교통거점",
      "address": "서울특별시 중랑구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.802,
      "is_fallback": false
    },
    {
      "place_name": "먹골역 7번출구 앞",
      "district": "중랑구",
      "district_normalized": "중랑구",
      "place_type": "교통거점",
      "address": "서울특별시 중랑구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.802,
      "is_fallback": false
    },
    {
      "place_name": "용마폭포공원",
      "district": "중랑구",
      "district_normalized": "중랑구",
      "place_type": "공원",
      "address": "서울특별시 중랑구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.785,
      "is_fallback": false
    },
    {
      "place_name": "봉화산근린공원",
      "district": "중랑구",
      "district_normalized": "중랑구",
      "place_type": "공원",
      "address": "서울특별시 중랑구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7387,
      "is_fallback": false
    },
    {
      "place_name": "용마도시자연공원(사가정공원)",
      "district": "중랑구",
      "district_normalized": "중랑구",
      "place_type": "공원",
      "address": "서울특별시 중랑구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7375,
      "is_fallback": false
    },
    {
      "place_name": "서일대뒷산공원",
      "district": "중랑구",
      "district_normalized": "중랑구",
      "place_type": "공원",
      "address": "서울특별시 중랑구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.735,
      "is_fallback": false
    },
    {
      "place_name": "면목역 광장",
      "district": "중랑구",
      "district_normalized": "중랑구",
      "place_type": "교통거점",
      "address": "서울특별시 중랑구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7089,
      "is_fallback": false
    }
  ],
  "성북구": [
    {
      "place_name": "정릉공영차고지",
      "district": "성북구",
      "district_normalized": "성북구",
      "place_type": "교통거점",
      "address": "서울특별시 성북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.802,
      "is_fallback": false
    },
    {
      "place_name": "성신여대입구",
      "district": "성북구",
      "district_normalized": "성북구",
      "place_type": "교통거점",
      "address": "서울특별시 성북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "장위14주택재개발구역",
      "district": "성북구",
      "district_normalized": "성북구",
      "place_type": "교통거점",
      "address": "서울특별시 성북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7649,
      "is_fallback": false
    },
    {
      "place_name": "성북천 상점가",
      "district": "성북구",
      "district_normalized": "성북구",
      "place_type": "전통시장",
      "address": "서울특별시 성북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5743,
      "is_fallback": false
    },
    {
      "place_name": "상경청년 자취방",
      "district": "성북구",
      "district_normalized": "성북구",
      "place_type": "전통시장",
      "address": "서울특별시 성북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4519,
      "is_fallback": false
    },
    {
      "place_name": "청량공원",
      "district": "성북구",
      "district_normalized": "성북구",
      "place_type": "공원",
      "address": "서울특별시 성북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3438,
      "is_fallback": false
    },
    {
      "place_name": "개운산근린공원",
      "district": "성북구",
      "district_normalized": "성북구",
      "place_type": "공원",
      "address": "서울특별시 성북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3322,
      "is_fallback": false
    },
    {
      "place_name": "성북근린공원",
      "district": "성북구",
      "district_normalized": "성북구",
      "place_type": "공원",
      "address": "서울특별시 성북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3182,
      "is_fallback": false
    }
  ],
  "강북구": [
    {
      "place_name": "삼양사거리",
      "district": "강북구",
      "district_normalized": "강북구",
      "place_type": "교통거점",
      "address": "서울특별시 강북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6985,
      "is_fallback": false
    },
    {
      "place_name": "수유역",
      "district": "강북구",
      "district_normalized": "강북구",
      "place_type": "교통거점",
      "address": "서울특별시 강북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6985,
      "is_fallback": false
    },
    {
      "place_name": "수유시장",
      "district": "강북구",
      "district_normalized": "강북구",
      "place_type": "전통시장",
      "address": "서울특별시 강북구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.538,
      "is_fallback": false
    },
    {
      "place_name": "북한산국립공원",
      "district": "강북구",
      "district_normalized": "강북구",
      "place_type": "공원",
      "address": "서울특별시 강북구, 도봉구, 서대문구, 성북구, 은평구, 종로구 일대  경기도 고양시, 양주시, 의정부시 일대",
      "lat": 37.624549,
      "lng": 127.000938,
      "source": "park_csv",
      "candidate_source": "park_csv",
      "score": 1.14,
      "is_fallback": false
    },
    {
      "place_name": "수유(강북구청)역 일대",
      "district": "강북구",
      "district_normalized": "강북구",
      "place_type": "교통거점",
      "address": "서울특별시 강북구 수유(강북구청)역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.0966,
      "is_fallback": false
    },
    {
      "place_name": "강북문화예술회관 일대",
      "district": "강북구",
      "district_normalized": "강북구",
      "place_type": "골목상권",
      "address": "서울특별시 강북구 강북문화예술회관 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9464,
      "is_fallback": false
    },
    {
      "place_name": "강북중학교 일대",
      "district": "강북구",
      "district_normalized": "강북구",
      "place_type": "골목상권",
      "address": "서울특별시 강북구 강북중학교 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9336,
      "is_fallback": false
    },
    {
      "place_name": "강북구청 일대",
      "district": "강북구",
      "district_normalized": "강북구",
      "place_type": "골목상권",
      "address": "서울특별시 강북구 강북구청 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9308,
      "is_fallback": false
    }
  ],
  "도봉구": [
    {
      "place_name": "초안산생태공원",
      "district": "도봉구",
      "district_normalized": "도봉구",
      "place_type": "공원",
      "address": "서울특별시 도봉구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.758,
      "is_fallback": false
    },
    {
      "place_name": "쌍문근린공원",
      "district": "도봉구",
      "district_normalized": "도봉구",
      "place_type": "공원",
      "address": "서울특별시 도봉구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7358,
      "is_fallback": false
    },
    {
      "place_name": "도봉산 입구",
      "district": "도봉구",
      "district_normalized": "도봉구",
      "place_type": "교통거점",
      "address": "서울특별시 도봉구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7089,
      "is_fallback": false
    },
    {
      "place_name": "박영선 지역유세장",
      "district": "도봉구",
      "district_normalized": "도봉구",
      "place_type": "교통거점",
      "address": "서울특별시 도봉구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7089,
      "is_fallback": false
    },
    {
      "place_name": "방학역",
      "district": "도봉구",
      "district_normalized": "도봉구",
      "place_type": "교통거점",
      "address": "서울특별시 도봉구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7089,
      "is_fallback": false
    },
    {
      "place_name": "월천근린공원",
      "district": "도봉구",
      "district_normalized": "도봉구",
      "place_type": "공원",
      "address": "서울특별시 도봉구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7046,
      "is_fallback": false
    },
    {
      "place_name": "도봉산 입구",
      "district": "도봉구",
      "district_normalized": "도봉구",
      "place_type": "공원",
      "address": "서울특별시 도봉구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6683,
      "is_fallback": false
    },
    {
      "place_name": "도봉산길",
      "district": "도봉구",
      "district_normalized": "도봉구",
      "place_type": "공원",
      "address": "서울특별시 도봉구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6683,
      "is_fallback": false
    }
  ],
  "노원구": [
    {
      "place_name": "구립수락노인종합복지관",
      "district": "노원구",
      "district_normalized": "노원구",
      "place_type": "복지시설",
      "address": "서울특별시 노원구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 2.065,
      "is_fallback": false
    },
    {
      "place_name": "수락산도시자연공원",
      "district": "노원구",
      "district_normalized": "노원구",
      "place_type": "공원",
      "address": "서울특별시 노원구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.746,
      "is_fallback": false
    },
    {
      "place_name": "불암산도시자연공원",
      "district": "노원구",
      "district_normalized": "노원구",
      "place_type": "공원",
      "address": "서울특별시 노원구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7432,
      "is_fallback": false
    },
    {
      "place_name": "경춘선 숲길",
      "district": "노원구",
      "district_normalized": "노원구",
      "place_type": "공원",
      "address": "서울특별시 노원구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6344,
      "is_fallback": false
    },
    {
      "place_name": "마들스포츠타운",
      "district": "노원구",
      "district_normalized": "노원구",
      "place_type": "공원",
      "address": "서울특별시 노원구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6344,
      "is_fallback": false
    },
    {
      "place_name": "불암산철쭉동산",
      "district": "노원구",
      "district_normalized": "노원구",
      "place_type": "공원",
      "address": "서울특별시 노원구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6344,
      "is_fallback": false
    },
    {
      "place_name": "공릉도깨비시장",
      "district": "노원구",
      "district_normalized": "노원구",
      "place_type": "전통시장",
      "address": "서울특별시 노원구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5438,
      "is_fallback": false
    },
    {
      "place_name": "롯데백화점 앞",
      "district": "노원구",
      "district_normalized": "노원구",
      "place_type": "교통거점",
      "address": "서울특별시 노원구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.528,
      "is_fallback": false
    }
  ],
  "은평구": [
    {
      "place_name": "연신내역",
      "district": "은평구",
      "district_normalized": "은평구",
      "place_type": "교통거점",
      "address": "서울특별시 은평구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7089,
      "is_fallback": false
    },
    {
      "place_name": "불광천",
      "district": "은평구",
      "district_normalized": "은평구",
      "place_type": "공원",
      "address": "서울특별시 은평구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.641,
      "is_fallback": false
    },
    {
      "place_name": "연신내역 일대",
      "district": "은평구",
      "district_normalized": "은평구",
      "place_type": "교통거점",
      "address": "서울특별시 은평구 연신내역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.1186,
      "is_fallback": false
    },
    {
      "place_name": "은평요양병원 일대",
      "district": "은평구",
      "district_normalized": "은평구",
      "place_type": "골목상권",
      "address": "서울특별시 은평구 은평요양병원 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9089,
      "is_fallback": false
    },
    {
      "place_name": "응암오거리상점가",
      "district": "은평구",
      "district_normalized": "은평구",
      "place_type": "전통시장",
      "address": "서울시 은평구 응암로9길6-15 응암오거리상점가",
      "lat": null,
      "lng": null,
      "source": "market_csv",
      "candidate_source": "market_csv",
      "score": 0.908,
      "is_fallback": false
    },
    {
      "place_name": "증산종합시장",
      "district": "은평구",
      "district_normalized": "은평구",
      "place_type": "전통시장",
      "address": "서울시 은평구 증산로3길 12 증산시장",
      "lat": null,
      "lng": null,
      "source": "market_csv",
      "candidate_source": "market_csv",
      "score": 0.9066,
      "is_fallback": false
    },
    {
      "place_name": "연서시장",
      "district": "은평구",
      "district_normalized": "은평구",
      "place_type": "전통시장",
      "address": "서울시 은평구 불광동 850 2층 연서시장",
      "lat": null,
      "lng": null,
      "source": "market_csv",
      "candidate_source": "market_csv",
      "score": 0.9063,
      "is_fallback": false
    },
    {
      "place_name": "대림시장",
      "district": "은평구",
      "district_normalized": "은평구",
      "place_type": "전통시장",
      "address": "서울시 은평구 응암로 4길 22 대림시장",
      "lat": null,
      "lng": null,
      "source": "market_csv",
      "candidate_source": "market_csv",
      "score": 0.9046,
      "is_fallback": false
    }
  ],
  "서대문구": [
    {
      "place_name": "국민은행 홍제동점",
      "district": "서대문구",
      "district_normalized": "서대문구",
      "place_type": "교통거점",
      "address": "서울특별시 서대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "홍제역",
      "district": "서대문구",
      "district_normalized": "서대문구",
      "place_type": "교통거점",
      "address": "서울특별시 서대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "궁동근린공원",
      "district": "서대문구",
      "district_normalized": "서대문구",
      "place_type": "공원",
      "address": "서울특별시 서대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7722,
      "is_fallback": false
    },
    {
      "place_name": "가좌역광장",
      "district": "서대문구",
      "district_normalized": "서대문구",
      "place_type": "교통거점",
      "address": "서울특별시 서대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.766,
      "is_fallback": false
    },
    {
      "place_name": "홍제천 인공폭포",
      "district": "서대문구",
      "district_normalized": "서대문구",
      "place_type": "공원",
      "address": "서울특별시 서대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.766,
      "is_fallback": false
    },
    {
      "place_name": "독립근린공원",
      "district": "서대문구",
      "district_normalized": "서대문구",
      "place_type": "공원",
      "address": "서울특별시 서대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7212,
      "is_fallback": false
    },
    {
      "place_name": "인왕시장",
      "district": "서대문구",
      "district_normalized": "서대문구",
      "place_type": "전통시장",
      "address": "서울특별시 서대문구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5383,
      "is_fallback": false
    },
    {
      "place_name": "서대문역 일대",
      "district": "서대문구",
      "district_normalized": "서대문구",
      "place_type": "교통거점",
      "address": "서울특별시 서대문구 서대문역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 0.9887,
      "is_fallback": false
    }
  ],
  "마포구": [
    {
      "place_name": "마포구 월드컵로 251",
      "district": "마포구",
      "district_normalized": "마포구",
      "place_type": "공원",
      "address": "서울특별시 마포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6509,
      "is_fallback": false
    },
    {
      "place_name": "상암동 월드컵공원",
      "district": "마포구",
      "district_normalized": "마포구",
      "place_type": "공원",
      "address": "서울특별시 마포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6509,
      "is_fallback": false
    },
    {
      "place_name": "서울월드컵경기장",
      "district": "마포구",
      "district_normalized": "마포구",
      "place_type": "공원",
      "address": "서울특별시 마포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6509,
      "is_fallback": false
    },
    {
      "place_name": "망원시장, 월드컵시장",
      "district": "마포구",
      "district_normalized": "마포구",
      "place_type": "전통시장",
      "address": "서울특별시 마포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5543,
      "is_fallback": false
    },
    {
      "place_name": "홍대거리",
      "district": "마포구",
      "district_normalized": "마포구",
      "place_type": "전통시장",
      "address": "서울특별시 마포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5543,
      "is_fallback": false
    },
    {
      "place_name": "상암",
      "district": "마포구",
      "district_normalized": "마포구",
      "place_type": "교통거점",
      "address": "서울특별시 마포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4474,
      "is_fallback": false
    },
    {
      "place_name": "여의도공원 10번 출구",
      "district": "마포구",
      "district_normalized": "마포구",
      "place_type": "교통거점",
      "address": "서울특별시 마포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4474,
      "is_fallback": false
    },
    {
      "place_name": "홍대상상마당",
      "district": "마포구",
      "district_normalized": "마포구",
      "place_type": "교통거점",
      "address": "서울특별시 마포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4474,
      "is_fallback": false
    }
  ],
  "양천구": [
    {
      "place_name": "파리공원",
      "district": "양천구",
      "district_normalized": "양천구",
      "place_type": "공원",
      "address": "서울특별시 양천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.802,
      "is_fallback": false
    },
    {
      "place_name": "목동 재건축 현장",
      "district": "양천구",
      "district_normalized": "양천구",
      "place_type": "교통거점",
      "address": "서울특별시 양천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "신정차량사업소",
      "district": "양천구",
      "district_normalized": "양천구",
      "place_type": "교통거점",
      "address": "서울특별시 양천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "양천공영차고지",
      "district": "양천구",
      "district_normalized": "양천구",
      "place_type": "교통거점",
      "address": "서울특별시 양천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "현대백화점 목동점",
      "district": "양천구",
      "district_normalized": "양천구",
      "place_type": "교통거점",
      "address": "서울특별시 양천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "양재천 수변무대",
      "district": "양천구",
      "district_normalized": "양천구",
      "place_type": "공원",
      "address": "서울특별시 양천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.766,
      "is_fallback": false
    },
    {
      "place_name": "양재천 수변무대 일대",
      "district": "양천구",
      "district_normalized": "양천구",
      "place_type": "공원",
      "address": "서울특별시 양천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.766,
      "is_fallback": false
    },
    {
      "place_name": "양천향교역 일대",
      "district": "양천구",
      "district_normalized": "양천구",
      "place_type": "교통거점",
      "address": "서울특별시 양천구 양천향교역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 0.9731,
      "is_fallback": false
    }
  ],
  "강서구": [
    {
      "place_name": "마곡나루역",
      "district": "강서구",
      "district_normalized": "강서구",
      "place_type": "교통거점",
      "address": "서울특별시 강서구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7089,
      "is_fallback": false
    },
    {
      "place_name": "마곡 LG사이언스파크 ISC동",
      "district": "강서구",
      "district_normalized": "강서구",
      "place_type": "전통시장",
      "address": "서울특별시 강서구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4065,
      "is_fallback": false
    },
    {
      "place_name": "화곡역 일대",
      "district": "강서구",
      "district_normalized": "강서구",
      "place_type": "교통거점",
      "address": "서울특별시 강서구 화곡역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.0791,
      "is_fallback": false
    },
    {
      "place_name": "까치산역 일대",
      "district": "강서구",
      "district_normalized": "강서구",
      "place_type": "교통거점",
      "address": "서울특별시 강서구 까치산역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.0767,
      "is_fallback": false
    },
    {
      "place_name": "강서구청 일대",
      "district": "강서구",
      "district_normalized": "강서구",
      "place_type": "골목상권",
      "address": "서울특별시 강서구 강서구청 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9438,
      "is_fallback": false
    },
    {
      "place_name": "강서고등학교 일대",
      "district": "강서구",
      "district_normalized": "강서구",
      "place_type": "골목상권",
      "address": "서울특별시 강서구 강서고등학교 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9294,
      "is_fallback": false
    },
    {
      "place_name": "강서수산시장 골목형상점가",
      "district": "강서구",
      "district_normalized": "강서구",
      "place_type": "전통시장",
      "address": "서울 강서구 발산로 24 수협공판장",
      "lat": null,
      "lng": null,
      "source": "market_csv",
      "candidate_source": "market_csv",
      "score": 0.9292,
      "is_fallback": false
    },
    {
      "place_name": "강서구다솔마을 일대",
      "district": "강서구",
      "district_normalized": "강서구",
      "place_type": "골목상권",
      "address": "서울특별시 강서구 강서구다솔마을 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.907,
      "is_fallback": false
    }
  ],
  "구로구": [
    {
      "place_name": "궁동종합사회복지관",
      "district": "구로구",
      "district_normalized": "구로구",
      "place_type": "복지시설",
      "address": "서울특별시 구로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 2.041,
      "is_fallback": false
    },
    {
      "place_name": "온수역",
      "district": "구로구",
      "district_normalized": "구로구",
      "place_type": "교통거점",
      "address": "서울특별시 구로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5651,
      "is_fallback": false
    },
    {
      "place_name": "베다니교회 앞",
      "district": "구로구",
      "district_normalized": "구로구",
      "place_type": "교통거점",
      "address": "서울특별시 구로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5408,
      "is_fallback": false
    },
    {
      "place_name": "온수도시자연공원",
      "district": "구로구",
      "district_normalized": "구로구",
      "place_type": "공원",
      "address": "서울특별시 구로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3365,
      "is_fallback": false
    },
    {
      "place_name": "고척근린공원",
      "district": "구로구",
      "district_normalized": "구로구",
      "place_type": "공원",
      "address": "서울특별시 구로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3349,
      "is_fallback": false
    },
    {
      "place_name": "개웅산근린공원",
      "district": "구로구",
      "district_normalized": "구로구",
      "place_type": "공원",
      "address": "서울특별시 구로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3241,
      "is_fallback": false
    },
    {
      "place_name": "고척1동 이동약자 현장",
      "district": "구로구",
      "district_normalized": "구로구",
      "place_type": "전통시장",
      "address": "서울특별시 구로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3241,
      "is_fallback": false
    },
    {
      "place_name": "푸른수목원",
      "district": "구로구",
      "district_normalized": "구로구",
      "place_type": "공원",
      "address": "서울특별시 구로구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3164,
      "is_fallback": false
    }
  ],
  "금천구": [
    {
      "place_name": "시티렉스 앞",
      "district": "금천구",
      "district_normalized": "금천구",
      "place_type": "교통거점",
      "address": "서울특별시 금천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6719,
      "is_fallback": false
    },
    {
      "place_name": "금천현대시장",
      "district": "금천구",
      "district_normalized": "금천구",
      "place_type": "전통시장",
      "address": "서울특별시 금천구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5412,
      "is_fallback": false
    },
    {
      "place_name": "가산디지털단지역 일대",
      "district": "금천구",
      "district_normalized": "금천구",
      "place_type": "교통거점",
      "address": "서울특별시 금천구 가산디지털단지역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.0633,
      "is_fallback": false
    },
    {
      "place_name": "금천구청역 일대",
      "district": "금천구",
      "district_normalized": "금천구",
      "place_type": "교통거점",
      "address": "서울특별시 금천구 금천구청역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 0.9743,
      "is_fallback": false
    },
    {
      "place_name": "금천해태공원 일대",
      "district": "금천구",
      "district_normalized": "금천구",
      "place_type": "골목상권",
      "address": "서울특별시 금천구 금천해태공원 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9339,
      "is_fallback": false
    },
    {
      "place_name": "금천세무서 일대",
      "district": "금천구",
      "district_normalized": "금천구",
      "place_type": "골목상권",
      "address": "서울특별시 금천구 금천세무서 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9274,
      "is_fallback": false
    },
    {
      "place_name": "삼성산자연공원(서울금천초등학교) 일대",
      "district": "금천구",
      "district_normalized": "금천구",
      "place_type": "골목상권",
      "address": "서울특별시 금천구 삼성산자연공원(서울금천초등학교) 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 0.9242,
      "is_fallback": false
    },
    {
      "place_name": "독산동 맛나는거리상점가",
      "district": "금천구",
      "district_normalized": "금천구",
      "place_type": "전통시장",
      "address": "서울특별시 시흥대로 398 ~ 독산로 247 독산동 맛나는거리상점가",
      "lat": null,
      "lng": null,
      "source": "market_csv",
      "candidate_source": "market_csv",
      "score": 0.9181,
      "is_fallback": false
    }
  ],
  "영등포구": [
    {
      "place_name": "광야홈리스복지센터",
      "district": "영등포구",
      "district_normalized": "영등포구",
      "place_type": "복지시설",
      "address": "서울특별시 영등포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 2.0307,
      "is_fallback": false
    },
    {
      "place_name": "샛강생태공원",
      "district": "영등포구",
      "district_normalized": "영등포구",
      "place_type": "공원",
      "address": "서울특별시 영등포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6922,
      "is_fallback": false
    },
    {
      "place_name": "여의도공원 10번 출구",
      "district": "영등포구",
      "district_normalized": "영등포구",
      "place_type": "교통거점",
      "address": "서울특별시 영등포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6922,
      "is_fallback": false
    },
    {
      "place_name": "여의도공원 3동 무궁화화장실",
      "district": "영등포구",
      "district_normalized": "영등포구",
      "place_type": "공원",
      "address": "서울특별시 영등포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6922,
      "is_fallback": false
    },
    {
      "place_name": "여의도공원 3동 무궁화화장실 앞",
      "district": "영등포구",
      "district_normalized": "영등포구",
      "place_type": "공원",
      "address": "서울특별시 영등포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6922,
      "is_fallback": false
    },
    {
      "place_name": "타임스퀘어",
      "district": "영등포구",
      "district_normalized": "영등포구",
      "place_type": "교통거점",
      "address": "서울특별시 영등포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6562,
      "is_fallback": false
    },
    {
      "place_name": "대림1구역 재개발 현장",
      "district": "영등포구",
      "district_normalized": "영등포구",
      "place_type": "교통거점",
      "address": "서울특별시 영등포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5978,
      "is_fallback": false
    },
    {
      "place_name": "영등포전통시장 남문",
      "district": "영등포구",
      "district_normalized": "영등포구",
      "place_type": "전통시장",
      "address": "서울특별시 영등포구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5905,
      "is_fallback": false
    }
  ],
  "동작구": [
    {
      "place_name": "보라매공원",
      "district": "동작구",
      "district_normalized": "동작구",
      "place_type": "공원",
      "address": "서울특별시 동작구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6963,
      "is_fallback": false
    },
    {
      "place_name": "남성사계시장",
      "district": "동작구",
      "district_normalized": "동작구",
      "place_type": "전통시장",
      "address": "서울특별시 동작구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5566,
      "is_fallback": false
    },
    {
      "place_name": "남성시장",
      "district": "동작구",
      "district_normalized": "동작구",
      "place_type": "전통시장",
      "address": "서울특별시 동작구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5566,
      "is_fallback": false
    },
    {
      "place_name": "노량진수산시장",
      "district": "동작구",
      "district_normalized": "동작구",
      "place_type": "전통시장",
      "address": "서울특별시 동작구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5566,
      "is_fallback": false
    },
    {
      "place_name": "이수역 14번 출구",
      "district": "동작구",
      "district_normalized": "동작구",
      "place_type": "교통거점",
      "address": "서울특별시 동작구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5282,
      "is_fallback": false
    },
    {
      "place_name": "사당역 일대",
      "district": "동작구",
      "district_normalized": "동작구",
      "place_type": "교통거점",
      "address": "서울특별시 동작구 사당역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.1021,
      "is_fallback": false
    },
    {
      "place_name": "신대방역 일대",
      "district": "동작구",
      "district_normalized": "동작구",
      "place_type": "교통거점",
      "address": "서울특별시 동작구 신대방역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.059,
      "is_fallback": false
    },
    {
      "place_name": "동작(현충원)역 일대",
      "district": "동작구",
      "district_normalized": "동작구",
      "place_type": "교통거점",
      "address": "서울특별시 동작구 동작(현충원)역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 0.9297,
      "is_fallback": false
    }
  ],
  "관악구": [
    {
      "place_name": "서울농산관",
      "district": "관악구",
      "district_normalized": "관악구",
      "place_type": "교통거점",
      "address": "서울특별시 관악구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6469,
      "is_fallback": false
    },
    {
      "place_name": "도림천",
      "district": "관악구",
      "district_normalized": "관악구",
      "place_type": "공원",
      "address": "서울특별시 관악구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5098,
      "is_fallback": false
    },
    {
      "place_name": "신림역 일대",
      "district": "관악구",
      "district_normalized": "관악구",
      "place_type": "교통거점",
      "address": "서울특별시 관악구 신림역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.2186,
      "is_fallback": false
    },
    {
      "place_name": "서울대입구(관악구청)역 일대",
      "district": "관악구",
      "district_normalized": "관악구",
      "place_type": "교통거점",
      "address": "서울특별시 관악구 서울대입구(관악구청)역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.1522,
      "is_fallback": false
    },
    {
      "place_name": "낙성대(강감찬)역 일대",
      "district": "관악구",
      "district_normalized": "관악구",
      "place_type": "교통거점",
      "address": "서울특별시 관악구 낙성대(강감찬)역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.0664,
      "is_fallback": false
    },
    {
      "place_name": "관악구 중앙길 일대",
      "district": "관악구",
      "district_normalized": "관악구",
      "place_type": "골목상권",
      "address": "서울특별시 관악구 관악구 중앙길 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 1.0542,
      "is_fallback": false
    },
    {
      "place_name": "봉천역 일대",
      "district": "관악구",
      "district_normalized": "관악구",
      "place_type": "교통거점",
      "address": "서울특별시 관악구 봉천역 일대",
      "lat": null,
      "lng": null,
      "source": "subway_csv",
      "candidate_source": "subway_csv",
      "score": 1.0541,
      "is_fallback": false
    },
    {
      "place_name": "신림역(신림) 일대",
      "district": "관악구",
      "district_normalized": "관악구",
      "place_type": "골목상권",
      "address": "서울특별시 관악구 신림역(신림) 일대",
      "lat": null,
      "lng": null,
      "source": "commercial_street_csv",
      "candidate_source": "commercial_street_csv",
      "score": 1.0338,
      "is_fallback": false
    }
  ],
  "서초구": [
    {
      "place_name": "문화예술공원",
      "district": "서초구",
      "district_normalized": "서초구",
      "place_type": "공원",
      "address": "서울특별시 서초구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7605,
      "is_fallback": false
    },
    {
      "place_name": "청계산도시자연공원",
      "district": "서초구",
      "district_normalized": "서초구",
      "place_type": "공원",
      "address": "서울특별시 서초구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.756,
      "is_fallback": false
    },
    {
      "place_name": "우면산도시자연공원",
      "district": "서초구",
      "district_normalized": "서초구",
      "place_type": "공원",
      "address": "서울특별시 서초구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7555,
      "is_fallback": false
    },
    {
      "place_name": "인능산도시자연공원",
      "district": "서초구",
      "district_normalized": "서초구",
      "place_type": "공원",
      "address": "서울특별시 서초구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7497,
      "is_fallback": false
    },
    {
      "place_name": "구룡산도시자연공원",
      "district": "서초구",
      "district_normalized": "서초구",
      "place_type": "공원",
      "address": "서울특별시 서초구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7495,
      "is_fallback": false
    },
    {
      "place_name": "매헌시민의숲",
      "district": "서초구",
      "district_normalized": "서초구",
      "place_type": "공원",
      "address": "서울특별시 서초구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7318,
      "is_fallback": false
    },
    {
      "place_name": "예술의전당",
      "district": "서초구",
      "district_normalized": "서초구",
      "place_type": "공원",
      "address": "서울특별시 서초구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7294,
      "is_fallback": false
    },
    {
      "place_name": "잠수교",
      "district": "서초구",
      "district_normalized": "서초구",
      "place_type": "공원",
      "address": "서울특별시 서초구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7294,
      "is_fallback": false
    }
  ],
  "강남구": [
    {
      "place_name": "GTX-A 삼성역 부실공사 현장",
      "district": "강남구",
      "district_normalized": "강남구",
      "place_type": "교통거점",
      "address": "서울특별시 강남구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7109,
      "is_fallback": false
    },
    {
      "place_name": "개포동 시장",
      "district": "강남구",
      "district_normalized": "강남구",
      "place_type": "전통시장",
      "address": "서울특별시 강남구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5612,
      "is_fallback": false
    },
    {
      "place_name": "개포우성7차아파트 1015~105동 사이",
      "district": "강남구",
      "district_normalized": "강남구",
      "place_type": "교통거점",
      "address": "서울특별시 강남구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4699,
      "is_fallback": false
    },
    {
      "place_name": "강남스퀘어",
      "district": "강남구",
      "district_normalized": "강남구",
      "place_type": "교통거점",
      "address": "서울특별시 강남구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4499,
      "is_fallback": false
    },
    {
      "place_name": "강남역",
      "district": "강남구",
      "district_normalized": "강남구",
      "place_type": "교통거점",
      "address": "서울특별시 강남구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4499,
      "is_fallback": false
    },
    {
      "place_name": "수서역 만남의 광장",
      "district": "강남구",
      "district_normalized": "강남구",
      "place_type": "교통거점",
      "address": "서울특별시 강남구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.4499,
      "is_fallback": false
    },
    {
      "place_name": "율현공원",
      "district": "강남구",
      "district_normalized": "강남구",
      "place_type": "공원",
      "address": "서울특별시 강남구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3472,
      "is_fallback": false
    },
    {
      "place_name": "대모산도시자연공원",
      "district": "강남구",
      "district_normalized": "강남구",
      "place_type": "공원",
      "address": "서울특별시 강남구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.3464,
      "is_fallback": false
    }
  ],
  "송파구": [
    {
      "place_name": "송파 거여새마을지구 공공재개발 현장",
      "district": "송파구",
      "district_normalized": "송파구",
      "place_type": "교통거점",
      "address": "서울특별시 송파구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.896,
      "is_fallback": false
    },
    {
      "place_name": "재개발·재건축 현장",
      "district": "송파구",
      "district_normalized": "송파구",
      "place_type": "교통거점",
      "address": "서울특별시 송파구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.874,
      "is_fallback": false
    },
    {
      "place_name": "잠실보조경기장",
      "district": "송파구",
      "district_normalized": "송파구",
      "place_type": "공원",
      "address": "서울특별시 송파구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6929,
      "is_fallback": false
    },
    {
      "place_name": "잠실실내체육관",
      "district": "송파구",
      "district_normalized": "송파구",
      "place_type": "공원",
      "address": "서울특별시 송파구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6929,
      "is_fallback": false
    },
    {
      "place_name": "잠실종합운동장",
      "district": "송파구",
      "district_normalized": "송파구",
      "place_type": "공원",
      "address": "서울특별시 송파구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6929,
      "is_fallback": false
    },
    {
      "place_name": "잠실학생체육관",
      "district": "송파구",
      "district_normalized": "송파구",
      "place_type": "공원",
      "address": "서울특별시 송파구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6929,
      "is_fallback": false
    },
    {
      "place_name": "새마을전통시장",
      "district": "송파구",
      "district_normalized": "송파구",
      "place_type": "전통시장",
      "address": "서울특별시 송파구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.6151,
      "is_fallback": false
    },
    {
      "place_name": "가락몰 농수산물시장",
      "district": "송파구",
      "district_normalized": "송파구",
      "place_type": "전통시장",
      "address": "서울특별시 송파구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.5791,
      "is_fallback": false
    }
  ],
  "강동구": [
    {
      "place_name": "재개발·재건축 현장",
      "district": "강동구",
      "district_normalized": "강동구",
      "place_type": "교통거점",
      "address": "서울특별시 강동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.854,
      "is_fallback": false
    },
    {
      "place_name": "고덕비즈밸리역 공사현장",
      "district": "강동구",
      "district_normalized": "강동구",
      "place_type": "교통거점",
      "address": "서울특별시 강동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.802,
      "is_fallback": false
    },
    {
      "place_name": "일자산근린공원",
      "district": "강동구",
      "district_normalized": "강동구",
      "place_type": "공원",
      "address": "서울특별시 강동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.8,
      "is_fallback": false
    },
    {
      "place_name": "고덕비즈밸리",
      "district": "강동구",
      "district_normalized": "강동구",
      "place_type": "교통거점",
      "address": "서울특별시 강동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.782,
      "is_fallback": false
    },
    {
      "place_name": "천호근린공원",
      "district": "강동구",
      "district_normalized": "강동구",
      "place_type": "공원",
      "address": "서울특별시 강동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7579,
      "is_fallback": false
    },
    {
      "place_name": "길동생태공원",
      "district": "강동구",
      "district_normalized": "강동구",
      "place_type": "공원",
      "address": "서울특별시 강동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7361,
      "is_fallback": false
    },
    {
      "place_name": "명일근린공원",
      "district": "강동구",
      "district_normalized": "강동구",
      "place_type": "공원",
      "address": "서울특별시 강동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7313,
      "is_fallback": false
    },
    {
      "place_name": "천호공원",
      "district": "강동구",
      "district_normalized": "강동구",
      "place_type": "공원",
      "address": "서울특별시 강동구 일대",
      "lat": null,
      "lng": null,
      "source": "public_csv",
      "candidate_source": "public_csv",
      "score": 1.7022,
      "is_fallback": false
    }
  ]
};
